### ISSUE TITLE
Is plowshare abendoned?

### ISSUE THREAD

**Issue by DavidXanatos** [mcrapet/plowshare-modules-legacy#1]
Since all modules are in the unmaintained section, there is a pressing question is plowshare abandoned and those not longer maintained?

**Comment by mcrapet** [comment]
Hi,
Plowshare (core) is still maintained. But modules (plowshare-modules-legacy repository) will be loosely maintained.
Websites (hosters) changes are very frequent and it requires a lot time. Maybe with github migration, contributions will be growing up!

**Comment by DavidXanatos** [comment]
well... the core is pointless without the modules :(
