### ISSUE TITLE
Zippyshare

### ISSUE THREAD

**Issue by PhunkyBob** [mcrapet/plowshare-modules-legacy#106]
Hello,

Zippyshare download does not work.
I've patched it this way (function "zippyshare_download"):
FROM:
http://pastebin.com/2Tabc6bp

TO:
http://pastebin.com/nSMaagkk

**Comment by frollic** [comment]
I confirm this bug/error:

/path/download.sh.29776.28090.js:22: ReferenceError: window is not defined
Output URL is not valid: http://www6.zippyshare.com

works after patching.

thank you PhunkyBob!

**Comment by mcrapet** [comment]
Thanks! Don't hesitate to create a PR.
