### ISSUE TITLE
Problem with MediaFire download

### ISSUE THREAD

**Issue by PhunkyBob** [mcrapet/plowshare-modules-legacy#109]
They change the URL style ("download" is replaced by "file").

Patch from
http://pastebin.com/KjtUEvqx
to
http://pastebin.com/tGirLxv2

And in the download function, patch from
http://pastebin.com/hjkvEu3H
to
http://pastebin.com/1a5jcmbJ

Best regards.

**Comment by mcrapet** [comment]
Hi, could you provide a patch ? (even better a PR)

**Comment by PhunkyBob** [comment]
I tried to make a PR, without success. 
I think I'm missing something. Do I have to clone the repo?

**Comment by mcrapet** [comment]
Yes, you'll have to fork my `plowshare-modules-legacy` repo, you see it on your own repos. Then clone it, push on it, and then create a pull request.

**Comment by mcrapet** [comment]
See also:
https://github.com/mcrapet/plowshare-modules-legacy/issues/103
https://github.com/mcrapet/plowshare-modules-legacy/issues/98
