### ISSUE TITLE
Zippyshare module needs update

### ISSUE THREAD

**Issue by dimitrinr** [mcrapet/plowshare-modules-legacy#111]
Starting on October 16th:

Starting download (zippyshare): http://www52.zippyshare.com/v/1cjbhBNc/file.html
Failed inside zippyshare_download() [141]

**Comment by zodman** [comment]
need more info ... pass -v 4 to the command

**Comment by PhunkyBob** [comment]
Problem is: people at ZippyShare look at this module. Each time a patch is provided, they change their website template to be incompatible with this module.

**Comment by mcrapet** [comment]
Is plowshare so widely used ? I don't think so...

**Comment by dimitrinr** [comment]
It appears to work if i comment out ' || return' part of the module.

diff --git a/zippyshare.sh b/zippyshare.sh
index aa6c1d2..b61e5f6 100644
--- a/zippyshare.sh
+++ b/zippyshare.sh
@@ -81,7 +81,7 @@ zippyshare_download() {
     detect_javascript || return

     # <meta property="og:title" content="... "
-    FILE_NAME=$(echo "$PAGE" | parse_attr '=.og:title.' content) || return
+    FILE_NAME=$(echo "$PAGE" | parse_attr '=.og:title.' content) #|| return
     test "$FILE_NAME" = 'Private file' && FILE_NAME=''

     if match 'var[[:space:]]*submitCaptcha' "$PAGE"; then

**Comment by mcrapet** [comment]
Hi,
Are you sure? I tested it with you URL and I do have:
`<meta property="og:title" content="linux Killing a process.pdf " />`

**Comment by zodman** [comment]
mmm last commit on master works for me ...

```
plowdown  'http://www52.zippyshare.com/v/1cjbhBNc/file.html' -v2
Starting download (zippyshare): http://www52.zippyshare.com/v/1cjbhBNc/file.html
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
File URL: http://www52.zippyshare.com/i/1cjbhBNc/97864/linux%20Killing%20a%20process.pdf
Filename: linux Killing a process.pdf
######################################################################## 100.0%
linux Killing a process.pdf

```

**Comment by mcrapet** [comment]
Seems there's no issue. Closing.
