### ISSUE TITLE
catshare.net

### ISSUE THREAD

**Issue by akxx87** [mcrapet/plowshare-modules-legacy#117]
Hello 
please fix Catshare.net premium

Login: 20GBmruczek362
Pass: nhbnrc94 

 plowdown -a 20GBmruczek362:nhbnrc94 http://catshare.net/fuXN17EuLeBFcTrf/Slub.od.pierwszego.wejrzenia.S01E09.PL.WEB-DL.XviD-YL4.avi
Starting download (catshare): http://catshare.net/fuXN17EuLeBFcTrf/Slub.od.pierwszego.wejrzenia.S01E09.PL.WEB-DL.XviD-YL4.avi
Starting login process: 20GBmruczek362/********
parse failed (sed): "/Konto:/ s/^.*\(Darmowe\|Premium\).*$/\1/p" (skip 1)
Failed inside catshare_login(), line 51, catshare.sh
Failed inside catshare_download() [1]

**Comment by akxx87** [comment]
can anyone help me?

**Comment by mcrapet** [comment]
Untested (Poland IP required).

**Comment by sargo** [comment]
@akxx87 could you please update plugins and test it again?
