### ISSUE TITLE
Turbobit download failed

### ISSUE THREAD

**Issue by kurand** [mcrapet/plowshare-modules-legacy#125]
Hi,

I get the following error when trying to download files from the turbobit.net:
plowdown http://turbobit.net/l5sqvgkqmi5x.html                                                                                                            
Starting download (turbobit): http://turbobit.net/l5sqvgkqmi5x.html
parse failed (sed): "/minLimit :/ s/^.*: \([[:digit:][:blank:]+-]\+\),.*$/\1/p" (skip 0)
Failed inside turbobit_download(), line 331, turbobit.sh
Failed inside turbobit_download() [1]

Please help me.

**Comment by rlaguilar** [comment]
Same here. I'm getting the same error

**Comment by mcrapet** [comment]
duplicate #102
