### ISSUE TITLE
Uptobox download issue Parse Failed

### ISSUE THREAD

**Issue by blephy** [mcrapet/plowshare-modules-legacy#127]
Hi,

Issue to download file from uptobox.
The first download i did from uptobox with plowdown did the job. But now, i'm getting this issue:

Starting download (uptobox): http://uptobox.com/$$$$$$$$$
parse failed (sed): "/start your download/ s/^.*href="\([^"]\+\)".*$/\1/p" (skip -2)
Failed inside uptobox_download(), line 260, uptobox.sh
Failed inside uptobox_download() [1]

thx

EDIT: ok, now i understand a bit more the fail. I try to download without -a argument and that's why the download worked on first plowdown, but not in next.
That's mean my plowshare.conf doens't work, or is not listen by plowshare. here is my .conf 

[General]
interface = enp2s0
verbose=3
[Plowdown]
uptobox/a=xxxxxxxx:xxxxxxxx++

Is there a mistake ?
my interface enp2s0 was find after ifconfig typing.

EDIT2: I copy my config file to /etc/plowshare.conf and now this work... seems other path is not looking by plowshare..

**Comment by mcrapet** [comment]
Hi,

<pre>$ man plowshare.conf
...
           ~/.config/plowshare/plowshare.conf
           /etc/plowshare.conf
...</pre>

Is there still an issue with uptobox ?

**Comment by blephy** [comment]
Hi,

There is no issue with my plowshare.conf anymore, cause i wrote my config in /etc/plowshare.conf instead of ~/.config/plowshare/plowshare.conf
Actually, my plowshare don't go to read the last one ... IDK why...

**Comment by mcrapet** [comment]
Do you have `$XDG_CONFIG_HOME` defined ?

**Comment by swiip81** [comment]
I think it is more about changes on the page, it is better with :

`sed -i 's/>You have to wait/you can wait/g;s/You have to wait/you can wait/' ~/.config/plowshare/modules/uptobox.sh`

**Comment by blephy** [comment]
@mcrapet: i don't think i specified this env variable
@swiip81: uptobox module is working properly, this is just about reading the config file.

Thanks for answers,  we can make the question closed.
