### ISSUE TITLE
Caching cookie with 1fichier module doesn't work any more

### ISSUE THREAD

**Issue by Konstantinusz** [mcrapet/plowshare-modules-legacy#129]

**Comment by zodman** [comment]
can you provide plow command with -v4 output plz

**Comment by Konstantinusz** [comment]
Last time when I tried it worked again. Maybe I had to update the modules. Sorry for false alarm.

**Comment by mcrapet** [comment]
Is this still relevant?

**Comment by zodman** [comment]
@mcrapet  i use to upload and download plz close this!

**Comment by mcrapet** [comment]
Ok thanks!
