### ISSUE TITLE
Error when I try to upload with multiup_org

### ISSUE THREAD

**Issue by kidburglar** [mcrapet/plowshare-modules-legacy#13]
First I did a git pull at my plowshare installation and a new make install.
After I do a plowmod -u to update legacy.git

When I try to upload a file, I grab this error.

$ plowup multiup_org file.ext
Starting upload (multiup_org): file.ext
Destination file: file.ext
parse_json failed (json): "hosts"
Failed inside multiup_org_upload(), line 90, multiup_org.sh
Failed inside multiup_org_upload() [1]

Thanks for your help.

**Comment by mcrapet** [comment]
Applyed!
