### ISSUE TITLE
Workupload

### ISSUE THREAD

**Issue by JayBrown** [mcrapet/plowshare-modules-legacy#133]
A workupload module would be most welcome: https://workupload.com

They have a lot of options, including setting email recipients, protecting share access with a password, setting maximum downloads and retention time… plus file deletion (deletion link valid for three hours). No account necessary, at least not for manual upload in the web browser.

**Comment by mcrapet** [comment]
plowshare is not maintained anymore. Not more module are added.
Status: Won't do.
