### ISSUE TITLE
Uptobox need update ?

### ISSUE THREAD

**Issue by Finch29** [mcrapet/plowshare-modules-legacy#135]
Hi, 
My upload to uptobox.com not work :( Maybe it's the new method for upload on there servers ? :s 

[Error screen](https://i.imgur.com/obcKTR8.png) 

Anyone as the same problem ? 

Thx in advance ;)

**Comment by hriad** [comment]
Same issue over here.

**Comment by Cinpph** [comment]
They change some things on the website, Uptobox module need a update.

**Comment by zodman** [comment]
+1 for me!

**Comment by zodman** [comment]
PR #137  yeah!

**Comment by Finch29** [comment]
Thx a lot @zodman :D !

**Comment by mcrapet** [comment]
Seems fixed, closing.

**Comment by ddurdle** [comment]
This error is back!

Seems the introduce a timeout at busy times where you have to wait 30 seconds for the button to appear useable.

**Comment by ddurdle** [comment]
I think the issue is the red text (in french) about 50% off premium for 15 euros.  If you use a premium account, it works, otherwise, it gets confused finding the link.

**Comment by mcrapet** [comment]
Hi,
I confirm that parsing of wait message is not good anymore.
