### ISSUE TITLE
Problem with plowhare calling from cron

### ISSUE THREAD

**Issue by Nordlicht123** [mcrapet/plowshare-modules-legacy#139]
Hi,
I've written the following scripts:
hoster.sh is the main script calling a other script hostercheck.sh.
The script hostercheck use plowdown to download files use a textfile with the hoster url's.
The textfiles with the hoster url's stored in a directory using also for ftp.
The cron job calling hoster.sh every minute. In the ftp directory a check of the existence of the textfile with the hoster url's proceed. If the textfile exists, the files downloaded with plowdown in the same ftp directory. After downloading the textfile with the hoster url's is deleted.
I use shareonline.biz and uploded.to with premium account.
 
A configuration file plowshare.conf (chmod 600 ~/.config/plowshare/plowshare.conf) is written as follows:
[General]
#interface = eth1
captchabhood=cbhuser:cbhpass
uploaded_net/a = xxxxx:yyyyy
shareonline_biz/a = aaaaaa:bbbbb
[Plowdown]
timeout=3600
#antigate=49b1b8740e4b51cf51838975de9e1c31
[Plowup]
max-retries=2
mirrorcreator/auth-free = foo:bar
mirrorcreator/count = 5
[Plowlist]
verbose = 3
 
If i call the main script hoster.sh manual via terminal/console as root the hoster url's (uploaded.to and share-online.biz) in the textfile plowdown works fine without any error, all files are downloaded.
 
If i call the same script from cron (root) calling with "0-59/1 * * * * /root/hoster.sh"
with the following parameters ($file is a link to a textfile with uploaded and shareonline links):
plowdown -m $file 2>&1 | tee /var/log/pddebug.out
 
The following debug information reported:
uploaded_net: take --auth option from configuration file
Starting download (uploaded_net): http://uploaded.net/file/r7rizis7
Starting login process: 12345678/********
parse failed (sed): "/Status:/ s/^.*<em>\(.*\)</em>.*$/\1/p" (skip 1)
Failed inside uploaded_net_login(), line 73, uploaded_net.sh
Failed inside uploaded_net_download() [1]
uploaded_net: take --auth option from configuration file
Starting download (uploaded_net): http://uploaded.net/file/0u8q0ywr
Same previous hoster, forced wait requested
Timeout reached (asked to wait 7200 seconds, but remaining time is 3600)
Delay limit reached (uploaded_net_download)
 
Only the share online files will be successfully downloaded.
For any help I would be grateful.

Stefan

**hoster.sh:**
#!/bin/bash

file="/var/www/ftp/abc/filelist.txt"
export file
./hostercheck.sh /var/log/hoster.log

file="/var/www/ftp/xyz/filelist.txt"
export file
./hostercheck.sh

**hostercheck.sh:**
#!/bin/bash
LOCKFILE=/tmp/$(whoami)_$(basename $0).lock
[ -f $LOCKFILE ] && { echo "$(basename $0) läuft schon"; exit 1; }

lock_file_loeschen() {
        rm -f $LOCKFILE
        echo lock-File $LOCKFILE gelöscht
}

trap "lock_file_loeschen ; exit 1" 2 9 15

echo "lege lock-File $LOCKFILE an"
echo $$ > $LOCKFILE

#NUM=1
# hier der Rest des Skripts

file=$file
fdir=$(dirname "$file")

if [ -f "$file" ]
then
        echo "$file found."
        cd $fdir
        plowdown -m $file 2>&1 | tee /var/log/pddebug.out
        rm $file
else
        echo "$file not found."
fi

lock_file_loeschen
exit 0

**Comment by mcrapet** [comment]
Hi Stefan,
According your logs, it seems that ùploaded_to` module is broken. Did you tried with other supported hosters (other than shareonline)?

**Comment by Nordlicht123** [comment]
Hi mcrape,
I have a premium account only for ul.to and share online. I didn't try other hosters. The manual script executing  via console work's without any problems, the script executing via cron fails only for uploaded.to. Very strange.

**Comment by mcrapet** [comment]
cron shell environment has less variables (PATH is different, USER not defined), but this should not have impact on modules.
Can you add  `verbose = 3` in `[Plowup]` section to have more log.

**Comment by Nordlicht123** [comment]
I've added in /etc/crontab the following line, the user:
0-59/1 * * * *  root    /root/hoster.sh
At least the user 'root' should now be defined.

The verbose = 3 entry in the Plowup section was added, because the log file is the same:
uploaded_net: take --auth option from configuration file
Starting download (uploaded_net): http://uploaded.net/file/r7rizis7
Starting login process: abcdefg/********
parse failed (sed): "/Status:/ s/^.*<em>\(.*\)</em>.*$/\1/p" (skip 1)
Failed inside uploaded_net_login(), line 73, uploaded_net.sh
Failed inside uploaded_net_download() [1]
uploaded_net: take --auth option from configuration file
Starting download (uploaded_net): http://uploaded.net/file/0u8q0ywr
Same previous hoster, forced wait requested
Timeout reached (asked to wait 7200 seconds, but remaining time is 3600)
Delay limit reached (uploaded_net_download)

**Comment by Nordlicht123** [comment]
I use plowdown in my script, is verbose = 3 in section [Plowdown] the better place ?

**Comment by Nordlicht123** [comment]
Log with verbose = 3 in [Plowdown] section:

dbg: plowdown: --captchabhood selected
uploaded_net: take --auth option from configuration file
Starting download (uploaded_net): http://uploaded.net/file/r7rizis7
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--$
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--$
Starting login process: abcdefg/********
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M100    23    0     0  100    23      0    156 --:--:-- --:--:-- --:--:--$
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--$
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M100  3733  100  3733    0     0  26586      0 --:--:-- --:--:-- --:--:--$
parse failed (sed): "/Status:/ s/^.*<em>\(.*\)</em>.*$/\1/p" (skip 1)
Failed inside uploaded_net_login(), line 73, uploaded_net.sh
Failed inside uploaded_net_download() [1]
uploaded_net: take --auth option from configuration file
Starting download (uploaded_net): http://uploaded.net/file/0u8q0ywr
Same previous hoster, forced wait requested
dbg: time left to timeout: 3600 secs
Timeout reached (asked to wait 7200 seconds, but remaining time is 3600)
Delay limit reached (uploaded_net_download)
dbg: retvals:1 5

**Comment by mcrapet** [comment]
Yes,could you try now with `verbose = 4`.

**Comment by Nordlicht123** [comment]
verbose = 4, personal data removed:
[pddebug.txt](https://github.com/mcrapet/plowshare-modules-legacy/files/869924/pddebug.txt)

**Comment by mcrapet** [comment]
I think that your modules sources are not up to date, update them.
You issue have been fixed with commit be12d96d9ceaaa3882522cc09f3508c3ddca02de (2016, may 9th).

**Comment by Nordlicht123** [comment]
I check the affected file uploaded_net.sh (./.config/plowshare/modules.d/legacy.git/uploaded_net.sh), and my file is up to date.
![uploaded_net_sh](https://cloud.githubusercontent.com/assets/26651260/24321853/0e483456-1157-11e7-8622-42e4b0786e91.png)

**Comment by mcrapet** [comment]
You can see log line:
`parse failed (sed): "/Status:/ s/^.(.).*$/\1/p" (skip 1)`
means that old module is used. 
Do you have modules in `/usr/share/plowshare4/modules` or `/usr/loca/share/plowshare4/modules`?

**Comment by mcrapet** [comment]
You plowshare v1.0.5 is quite old, could you update it.

**Comment by Nordlicht123** [comment]
You are right, old files exists in /usr/share/plowshare4. I don't know to change it. I install plowshare with apt-get install plowshare4.

**Comment by mcrapet** [comment]
`plowshare4` is old package name, should be `plowshare`. Read documentation ([INSTALL](https://raw.githubusercontent.com/mcrapet/plowshare/master/INSTALL) file)

**Comment by Nordlicht123** [comment]
I uninstall all old files and use the manual method described in the mentioned install file. Now, all works fine (console and cron). Thank you for your assistance.

**Comment by mcrapet** [comment]
Great!
