### ISSUE TITLE
OpenLOAD

### ISSUE THREAD

**Issue by normanfeltz** [mcrapet/plowshare-modules-legacy#141]
Hello,

I have a error on downloading on OpenLOAD
`
normanfeltz@srv:~$ plowdown https://openload.co/embed/F31CzCPMb0c/
Output directory: /home/Plex/_Downloads
Starting download (openload): https://openload.co/embed/F31CzCPMb0c/
parse failed (sed): "/fid=/ s/^.*"\(.*\)".*$/\1/p" (skip 0)
Failed inside openload_download(), line 84, openload.sh
Failed inside openload_download() [1]
`

Cordialy

**Comment by kidburglar** [comment]
My PR must make it work but the API have many limitation from what I see.
When I have time I will try to see if there is a possibility to use browser download when the API not work.
