### ISSUE TITLE
Rapidgator - unable to upload --- parse failed (sed): "/var form_url/ s/^.*"\(.\+\)";.*$/\1/p" (skip 0)

### ISSUE THREAD

**Issue by rlsblogse** [mcrapet/plowshare-modules-legacy#165]
hi,
i got that error when i try to upload anything on rapidgator.

Starting upload (rapidgator): American.Dad.S13E18.720p.HDTV.x264-AVS.mkv
Destination file: American.Dad.S13E18.720p.HDTV.x264-AVS.mkv
Starting login process: rutab%40yahoo.com/***
parse failed (sed): "/var form_url/ s/^.*"\(.\+\)";.*$/\1/p" (skip 0)
Failed inside rapidgator_upload(), line 644, rapidgator.sh
Failed inside rapidgator_upload() [1]

please fix the issue.

regards
bye.

**Comment by ohnoez** [comment]
Can someone fix this please? Same problem here

**Comment by rlsblogse** [comment]
its seems rapidgator force to use Https , maybe it is the problem,

**Comment by neeraj-m** [comment]
see my PR for a potential intermedia-fix for uploading:
https://github.com/mcrapet/plowshare-modules-legacy/pull/168

**Comment by ohnoez** [comment]
works, thanks

**Comment by rlsblogse** [comment]
thanks , yes it worked.
