### ISSUE TITLE
Plowshare doesn't work (uptobox)

### ISSUE THREAD

**Issue by Fu2chN** [mcrapet/plowshare-modules-legacy#177]
Hi
I can't use plowshare I fall on:

plowdown -a 'USER:PASSW' LINKSUPTOBOX
```
grep_form_by_name failed (sed): "name=F1"
Failed inside uptobox_download() [1]
```
plowup uptobox -a 'USER:PASSW' FILES
```
grep_form_by_id failed (sed): "id=fileupload"
Failed inside uptobox_upload() [1]
```

What is my mistake?

I install them like this:
```
apt-get install git curl -y
cd /tmp
git clone https://github.com/mcrapet/plowshare.git
cd plowshare
make install
cd ..
rm -rf plowshare
```

I'm on Debian 9

Thank for help.

**Comment by CMoranO** [comment]
the site was under maintenance

**Comment by mcrapet** [comment]
Ok. Closing.

**Comment by Fu2chN** [comment]
heu what ?

**Comment by Fu2chN** [comment]
It's online, this just a weekly maintenance.

Uptobox has juste executing a weekly maintenance. Who have nothing to do with my problem, so why close the ticket?

**Comment by mcrapet** [comment]
Hi,
You told that uptobox was not working. Then you said that uptobox site was under maintenance. So I deducted that it was not a plowshare module issue.

**Comment by mcrapet** [comment]
Please do read also: [this documentation](https://github.com/mcrapet/plowshare-modules-legacy/blob/master/CONTRIBUTING.md) to report broken module.
