### ISSUE TITLE
1fichier.com bug disconnects other session

### ISSUE THREAD

**Issue by andykimpe** [mcrapet/plowshare-modules-legacy#18]
when using  plowdown or plowup other session that are connected are automatically logged on 1fichier.com

This very annoying because it must always have reconnected

is it possible to disable the next option when plowshare performs the connection?

Long session

Restrict the session to my IP address

Purge old sessions 

view Advanced Options  on https://1fichier.com/login.pl?lg=en

thank you

**Comment by mcrapet** [comment]
> is it possible to disable the next option when plowshare performs the connection?

Cut and paste from plowshare README:

Use cache over sessions to avoid multiple logins:

<pre>
$ plowup --cache=shared -a 'user:pasword' 1fichier file1.zip
$ plowup --cache=shared 1fichier file2.zip
</pre>

On first command line, login stage will be performed and session (token or cookie) will be saved in ~/.config/plowshare/storage/module-name.txt. On second command line, plowup will reuse the data stored to bypass login step. You don't have to specify credentials.

Note: Only few hosters currently support cache mecanism.
