### ISSUE TITLE
UpToBox fails (16/02/18)

### ISSUE THREAD

**Issue by yaros98** [mcrapet/plowshare-modules-legacy#191]
UpToBox fails to this date. Seems like they changed a few things.

> Hello,
> 
> we recently made some changes and technical updates.
> plowshare will certainly deliver an update to make them
> compatible again.
> May I suggest you to contact them directly to get further informations.
> 
> Thank you
> 
> Regards
> 
> 
> Philippe
> Uptobox support

**Comment by celogeek** [comment]
The login part seems to use reCaptcha now. This part will be hard to pass though. I'm not sure it is possible to login to premium account outside the site anymore.

**Comment by celogeek** [comment]
I have made a demand for an API or something that will help premium user to get back the plowshare functionnality. Wait and see :)

**Comment by celogeek** [comment]
Well, I've got an answer. An API is in development progress. I think this way it will be easy to get back plowshare to work.
The admin say to use the cookie obtain from the website in the mean time.

**Comment by yaros98** [comment]
Thanks for checking @celogeek 
So UpToBox's module will be broken for a while...

**Comment by ddurdle** [comment]
There is no reason this should be broken.  They only changed their webpage displaying the link.

see: https://github.com/ddurdle/CloudStream-for-KODI/pull/20/commits/fcf7c4e9119ff556203d0f4ef707bf7aaa6e09ef

**Comment by skillfr** [comment]
if you have a premium account check Direct download, for others wait for a possible update of the plugin ....
![chrome_2018-02-26_22-12-01](https://user-images.githubusercontent.com/12272393/36695788-95648d68-1b42-11e8-96fe-1661cfa4f10b.png)

**Comment by ddurdle** [comment]
This was working for 1 day and now not anymore:

```
parse_tag failed (sed): "/title/ <title>"
Failed inside uptobox_cloudflare(), line 75, uptobox.sh
grep_form_by_name failed (sed): "name=F1"
Failed inside uptobox_download() [1]
```


The first two lines of error were not occurring the other day with direct enabled.  I was successfully able to download files, not anymore.

**Comment by zodman** [comment]
confirm bug!

**Comment by zodman** [comment]
Small change on the uptobox action url: action="//www74.uptobox.com/upload?sess_id="  break all

```
plowup uptobox LICENSE  -v 3

Starting upload (uptobox): LICENSE
Destination file: LICENSE
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3559    0  3559    0     0   6841      0 --:--:-- --:--:-- --:--:--  6844
dbg: //www74.uptobox.com/upload?sess_id=
dbg: debug html '<form id="fileupload" action="//www74.uptobox.com/upload?sess_id=" method="POST" enctype="multipart/form-data">
<div class='btn-action pb-5'>
<span class="big-button-green fileinput-button">
<i class="fa fa-plus" aria-hidden="true"></i>
Add Files...
<input type="file" name="files[]" multiple>
</span>
<span class='white big-button-green fileinput-button startAll'>
<i class="fa fa-arrow-circle-o-up" aria-hidden="true"></i>
Start
</span>
<button type='reset' class='white big-button-green cancel'>
<i class="fa fa-ban" aria-hidden="true"></i>
Cancel
</button>
<span class="fileupload-process"></span>
</div>
<div class="fileupload-progress upload-informations fade mb-5">
<div class="progress-extended">&nbsp;</div>
<div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
<div class="progress-bar progress-bar-success" style="width:0%;"></div>
</div>
</div>
<table role="presentation" class="files-container table table-striped">
<tbody class="files"></tbody>
</table>
</form>'
curl: (3) <url> malformed
curl: failed with exit code 3
Failed inside uptobox_upload() [3]

```

**Comment by zodman** [comment]
;) i rocks!

**Comment by zodman** [comment]
i confirm fix:

```
 plowup uptobox LICENSE

Starting upload (uptobox): LICENSE
Destination file: LICENSE
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 35602  100   157  100 35445    177  40090 --:--:-- --:--:-- --:--:-- 40141
#DEL http://uptobox.com/5ptsfgkkk9ha?killcode=02ad9e83e4
http://uptobox.com/5ptsfgkkk9ha
```

**Comment by zodman** [comment]
for the download  someone needs update the method ( i use uptobox for upload only)

**Comment by skillfr** [comment]
....

**Comment by shahwahed** [comment]
I've got a fix for download, but only tested on free account, I've havn't got a premium to debug premium one

**Comment by shahwahed** [comment]
someone can test my fix with a premium account? to fix it?

**Comment by skillfr** [comment]
@shahwahed yes, it works perfectly with a premium account.
![nvidia share_2018-03-10_22-29-18](https://user-images.githubusercontent.com/12272393/37253392-6305693e-2531-11e8-80cf-4380915a7ddc.png)
Thank you !

**Comment by shahwahed** [comment]
Great :)

**Comment by vgeannin** [comment]
I'm sorry but it doesn't work with premium account
the script doesn't retrieve the premium link, so the download speed is limited

Vincent

**Comment by ddurdle** [comment]
I ran into the same problem.  It was downloading slow and stopped working after that completely.  The process just hangs.

**Comment by skillfr** [comment]
@vgeannin and @ddurdle, it works perfectly with a premium account.

```
plowdown http://uptobox.com/87wjcrlfsfdh
uptobox: take --auth option from configuration file
Starting download (uptobox): http://uptobox.com/87wjcrlfsfdh
Starting login process: XXXX/**********
File URL: https://www19.uptobox.com/dl/xxxxxx/The.Walking.Dead.S08E08.VOSTFR.1080p.WEB-DL.DD5.1.H264-ARK01.mkv
Filename: The.Walking.Dead.S08E08.VOSTFR.1080p.WEB-DL.DD5.1.H264-ARK01.mkv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  8 2435M    8  217M    0     0  10.9M      0  0:03:41  0:00:19  0:03:22 11.2M^C
```

**Comment by shahwahed** [comment]
If you can send me debug output (-v4) so I can't debug, havn't get a premium account

**Comment by vgeannin** [comment]
Here is the logs

Vincent
[log.txt](https://github.com/mcrapet/plowshare-modules-legacy/files/1806300/log.txt)

**Comment by vgeannin** [comment]
OK, so I comment some part of the code and it work :
`    if [ "$PREMIUM" = '1' ]; then
        local FILE_URL

        #FORM_OP=$(parse_form_input_by_name 'op' <<< "$FORM_HTML") || return
        #FORM_ID=$(parse_form_input_by_name 'id' <<< "$FORM_HTML") || return
        #FORM_DD=$(parse_form_input_by_name_quiet 'down_direct' <<< "$FORM_HTML")
        #FORM_RAND=$(parse_form_input_by_name 'rand' <<< "$FORM_HTML") || return
        #FORM_METHOD=$(parse_form_input_by_name_quiet 'method_free' <<< "$FORM_HTML")

        #PAGE=$(curl -b "$COOKIE_FILE" -b 'lang=english' \
        #    -d "op=$FORM_OP" \
        #    -d "id=$FORM_ID" \
        #    -d "rand=$FORM_RAND" \
        #    -d 'method_free=' \
        #    -d "down_direct=${FORM_DD:+1}" \
        #    -d 'referer=' \
        #    -d "method_premium=$FORM_METHOD" "$URL") || return

        # Click here to start your download
        FILE_URL=$(parse_attr '/d/' 'href' <<< "$PAGE")
        if match_remote_url "$FILE_URL"; then
            echo "$FILE_URL"
            return 0
        fi
    fi
`

**Comment by skillfr** [comment]
lol ... it's normal you have to go into your uptobox account and activate Direct Download

I'm not done enough screenshot ?
![](https://user-images.githubusercontent.com/12272393/37253392-6305693e-2531-11e8-80cf-4380915a7ddc.png)

**Comment by shahwahed** [comment]
So let sum up.
premium account just configure your account properly : 
directdownload active
ssl active

and no form to send, just grab the direct download

**Comment by vgeannin** [comment]
yep it work with the correct configuration

Thanks

**Comment by skillfr** [comment]
@shahwahed Hi friend, we still need you! https://github.com/mcrapet/plowshare-modules-legacy/issues/197

**Comment by mcrapet** [comment]
Ok let's go to #197 !
