### ISSUE TITLE
bug connect uptobox

### ISSUE THREAD

**Issue by fullsharez** [mcrapet/plowshare-modules-legacy#197]
![uptobox](https://user-images.githubusercontent.com/26851213/37766919-bd4720a0-2dc8-11e8-89c1-f07ea24fc686.PNG)
Hello here is my problem identifying perfectly good I use plowshare to make the upload since that day its more works would you have an issue thank you

**Comment by fullsharez** [comment]
I do not understand I did not change anything in my account I did not activate the protection ssl etc in the account and last night it worked well and today it works more

**Comment by fullsharez** [comment]
ok now url for connect is https://uptobox.com/?op=login&referer=homepage not good loga....

**Comment by fullsharez** [comment]
ligne 275     if [ -n "$AUTH" ]; then
        uptobox_login "$AUTH" "$COOKIE_FILE" 'https://uptobox.com/?op=login&referer=homepage' || return
    fi

**Comment by skillfr** [comment]
nice https://github.com/mcrapet/plowshare-modules-legacy/commit/d018e8d1886d560b6a261f7b648f099656d906d2

**Comment by hriad** [comment]
It works with @fullsharez fix

**Comment by shahwahed** [comment]
great

**Comment by zodman** [comment]
@skillfr   commit works for me put the commit on master plz!

**Comment by zodman** [comment]
this works for me #199

**Comment by mcrapet** [comment]
Fixed by #200 
Thanks for your work.
