### ISSUE TITLE
chunk upload

### ISSUE THREAD

**Issue by vlafranca** [mcrapet/plowshare-modules-legacy#2]
Hi,
I am working on a module but i need to do chunk upload and unfortunately I did not manage to get it work.
Could you show me how I can process chunk upload using plowshare ?

Thanks in advance

**Comment by mcrapet** [comment]
What do you want to do exactly ?
There's no specific Plowshare API for that, you'll have to tell curl directly that you want to upload from byte n to byte m.

**Comment by vlafranca** [comment]
Hi,
I'm trying to upload large files on uplea.com because their system does not
accept files larger than 2000mb without chunks.
On their websites they are doing chucks of 100mb with a content-range
header but I don't manage to get this work on curl. Header line is well
present in request but seems to be ignored and the file does not upload
properly.

Thanks in advance for your help...

**Comment by mcrapet** [comment]
What about simply doing something like:
$ split -b 200M filename.rar 'newfilename.'
$ plowup uplea newfilename.*

**Comment by vlafranca** [comment]
I will get multiple download links, this is not the goal ...

**Comment by mcrapet** [comment]
There's no chunk mentioned in their API documentation.
http://uplea.com/api

More than 2G seems for premium account only.

**Comment by vlafranca** [comment]
Yes I know but I sent a mail and indeed it's not in the api but you can see
that in browser header inspector when you upload.

**Comment by mcrapet** [comment]
Close this old issue.
