### ISSUE TITLE
Uptobox not working

### ISSUE THREAD

**Issue by normanfeltz** [mcrapet/plowshare-modules-legacy#226]
Hello,

I have a error with Uptobox (I have a premium account).

![image](https://user-images.githubusercontent.com/1359159/52339467-79ec9500-2a0d-11e9-96e0-d136ee01fb05.png)

Cordialy

Norman FELTZ

**Comment by leloki** [comment]
Hi Norman,

please try to replace http by https in your link.
It works for me.

**Comment by jpwilsch** [comment]
There has been a change in uptobox my_account page, which broke the account type detection in the script.
Here's a pull request : 
https://github.com/mcrapet/plowshare-modules-legacy/pull/227

**Comment by normanfeltz** [comment]
Hi,

I have update the script and change http to https and it work !

Thanks !
