### ISSUE TITLE
Uptobox upload not working

### ISSUE THREAD

**Issue by ReshibanGaming** [mcrapet/plowshare-modules-legacy#230]
Hello, I have a problem with Uptobox.

I've installed Plowshare on my Raspberry Pi (Raspbian Stretch) and installed modules necessary to work.
I've linked my account, and the download perfectly work.

But the upload don't work.

Every times, he said that:
`grep_form_by_id failed (sed): "id=fileupload"`
`Failed inside uptobox_upload() [1]`

I am up to date, and there is no maintenance.

I think the script can be "broken" because "Extend premium" was "Get premium" or an other text, but I'm not sur.

If someone can help me, it's very cool! :)
(I'm french :p)

**Comment by ReshibanGaming** [comment]
Finaly, I think the problem is here
[https://ibb.co/xF7MY3N](url)
[https://ibb.co/JHjPdmp](url)

I've never using this language, so I cannot fix this, if someone can be that, that is cool :)

**Comment by ReshibanGaming** [comment]
Finaly, there is already a ticket with the solution here (that work)
https://github.com/mcrapet/plowshare-modules-legacy/issues/204

**Comment by Merlincool** [comment]
This is not working
