### ISSUE TITLE
Uptobox failed download when long waiting time

### ISSUE THREAD

**Issue by DamsDev1** [mcrapet/plowshare-modules-legacy#261]
Uptobox download fails all the time when I download with a long waiting time before (with the long waiting time) and when I am authenticated (no premium account)

Error:
`Waiting 1282 seconds... done`
`parse_attr failed (sed): "/<[Ii][Nn][Pp][Uu][Tt][^>]*name[[:space:]]*=[[:space:]]*["']\?waitingToken["']\?[[:space:]/>]/ value="`
`Failed inside parse_form_input_by_name(), line 601, core.sh`
`Failed inside uptobox_download(), line 154, uptobox.sh`
`Failed inside uptobox_download() [1]`

**Comment by bonnebulle** [comment]
Same issue here 
@DamsDev1 how do you fix ?
thanks all

**Comment by DamsDev1** [comment]
I've made a personnal Bash script, i don't have it anymore. You can use pyLoad, it's works very great for downloading (pyLoad can't upload). Or you can use rclone, it's the better tools for now.
