### ISSUE TITLE
uploaded_net.sh unable to upload or download

### ISSUE THREAD

**Issue by Hugendubelsfranz** [mcrapet/plowshare-modules-legacy#27]
hi, 

since yesterday i am unable to upload to uploaded.net oder download from uploaded.net:

uploaded_net: take --auth option from configuration file
Starting upload (uploaded_net): 123.part1.rar
Destination file: 123.part1.rar
parse failed (sed): "/uploadServer =/ s/^.*[[:space:]]'\([^']*\).*$/\1/p" (skip 0)
Failed inside uploaded_net_upload(), line 479, uploaded_net.sh
Failed inside uploaded_net_upload() [1]

plowdown: force captcha method (online)
uploaded_net: take --auth option from configuration file
Starting download (uploaded_net): http://ul.to/123456
curl: failed with exit code 56

**Comment by Drezzler** [comment]
Having the same problem here , i am working on a fix though .

**Comment by Drezzler** [comment]
This is only a hack i guess , as i cant figure out why is `grep_http_header_location` failing , to fix this issue , in `/var/share/plowshare4/mobules/uploaded_net.sh` replace 

`URL=$(curl -I -L "$2" | grep_http_header_location | last_line) || return
 [ -n "$URL" ] || URL=$2`

With 

`URL=$2`

And make sure you are passing all direct urls to plowshare , so url needs to `http://uploaded.net/file/file_id` format , as the above edit removes any url redirect detection .

**Comment by Hugendubelsfranz** [comment]
The plugin works again :) Error on uploaded.net side?
