### ISSUE TITLE
turbobit.sh module can't download files

### ISSUE THREAD

**Issue by jupy** [mcrapet/plowshare-modules-legacy#28]
Something changed on turbobit site, so now plowdown reports error:

parse failed (sed): "/<title>/ s/^[[:blank:]]*Download \(.\+\). Free.*$/\1/p" (skip 1)

**Comment by Drezzler** [comment]
This is happening with all modules , my guess is that these sites are switching to HTTP2 , which might be the cause of the problem , if are ok with editing files try the fix i posted here https://github.com/mcrapet/plowshare-modules-legacy/issues/27
