### ISSUE TITLE
1fichier.com module issue

### ISSUE THREAD

**Issue by f0c4l** [mcrapet/plowshare-modules-legacy#31]
rep: === SYSTEM INFO BEGIN ===
rep: [mach] raspberrypi arm linux-gnueabihf arm-unknown-linux-gnueabihf
rep: [bash] 4.3.30(1)-release

rep: [curl] curl 7.38.0 (arm-unknown-linux-gnueabihf) libcurl/7.38.0 OpenSSL/1.0.1k zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
rep: [sed ] License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
rep: [lib ] '/usr/share/plowshare'
rep: === SYSTEM INFO END ===
rep: plowdown version v2.1.2-5-g9c672cb (2015-11-21)
Starting download (1fichier): https://1fichier.com/?kvs8aox113
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0 --silent --head -b /tmp/plowdown.18825.1343 https://1fichier.com/?kvs8aox113
rep: Received 247 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep:HTTP/1.1 200 OK
rep:Server: nginx
rep:Date: Tue, 22 Dec 2015 22:36:55 GMT
rep:Content-Type: text/html; charset=utf-8
rep:Connection: keep-alive
rep:Vary: Accept-Encoding
rep:Cache-Control: no-cache
rep:Expires: Fri, 30 Oct 1998 14:19:41 GMT
rep:Content-Encoding: gzip
rep:
rep: === CURL END ===
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0 --silent --form-string links[]=https://1fichier.com/?kvs8aox113 https://1fichier.com/check_links.pl
rep: Received 135 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep:https://1fichier.com/?kvs8aox113;Ant-Man.2015.REAL.RERIP.MULTI.1080p.BluRay.x264.AC3.DTS-ShowFr.zone-telechargement.com.mkv;9785685538
rep: === CURL END ===
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0 --silent -b LG=en https://1fichier.com/?kvs8aox113
rep: Received 13211 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep:<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
rep:	"http://www.w3.org/TR/html4/strict.dtd">
rep:<html lang="en">
rep:	<head>
rep:    <title>1fichier.com: Cloud Storage</title>
rep:		<meta name="robots" content="noindex" />
rep:    <meta http-equiv="content-type" content="text/html;charset=utf-8">
rep:    <link rel="shortcut icon" href="https://img.1fichier.com/favicon.ico" />
rep:    <link rel="icon" type="image/x-icon" href="https://img.1fichier.com/favicon.ico" />
rep:    <link rel="icon" type="image/png" href="https://img.1fichier.com/favicon.png" />
rep:    <link rel="apple-touch-icon" href="https://img.1fichier.com/favicon.png" />
rep:    <link rel="image_src" href="https://img.1fichier.com/favicon.png" />
rep:    <link rel="stylesheet" type="text/css" href="https://img.1fichier.com/css/style.css" />
rep:    <link rel="stylesheet" type="text/css" href="https://img.1fichier.com/css/jquery.ui.css" />
rep:    <script type="text/javascript" src="https://img.1fichier.com/js/jquery.js"></script>
rep:
rep:		<script type="text/javascript">
rep:		</script>
rep:</head>
rep:<body>
rep:<div id="header" class="bloc">
rep:	<div class="center-container">
rep:		<a href="https://1fichier.com" title="1fichier.com"><img id="logo" src="https://img.1fichier.com/logo.png" alt="logo" width="240" height="70" style="margin-top:5px" /></a>
rep:
rep:		<div id="btn-container">
rep:			<div class="select-container ddh" style="width:150px">
rep:    		<select class="dropdown" onchange="window.location.href=this.value">
rep:		      <option value="/?kvs8aox113&amp;lg=fr" data-imagesrc="https://img.1fichier.com/flags/fr.png">Francais</option>
rep:    		  <option value="/?kvs8aox113&amp;lg=bg" data-imagesrc="https://img.1fichier.com/flags/bg.png">Български</option>
rep:		      <option value="/?kvs8aox113&amp;lg=cn" data-imagesrc="https://img.1fichier.com/flags/cn.png">中文（简体）</option>
rep:		      <option value="/?kvs8aox113&amp;lg=en" data-imagesrc="https://img.1fichier.com/flags/en.png" selected="selected">English</option>
rep:		      <option value="/?kvs8aox113&amp;lg=es" data-imagesrc="https://img.1fichier.com/flags/es.png">Español</option>
rep:		      <option value="/?kvs8aox113&amp;lg=in" data-imagesrc="https://img.1fichier.com/flags/in.png">हिंदी</option>
rep:		      <option value="/?kvs8aox113&amp;lg=pl" data-imagesrc="https://img.1fichier.com/flags/pl.png">Polski</option>
rep:					<option value="/?kvs8aox113&amp;lg=pt" data-imagesrc="https://img.1fichier.com/flags/pt.png">Português</option>
rep:		      <option value="/?kvs8aox113&amp;lg=tr" data-imagesrc="https://img.1fichier.com/flags/tr.png">Türkçe</option>
rep:					<option value="/?kvs8aox113&amp;lg=ru" data-imagesrc="https://img.1fichier.com/flags/ru.png">Русский</option>
rep:		    </select>
rep:			</div>
rep:
rep:			<a class="btn-general btn-gris-clair" href="https://1fichier.com/tarifs.html" title="Prices">Prices</a>
rep:
rep:			
rep:				<a class="btn-general btn-orange" href="https://1fichier.com/register.pl" title="Register">Register</a>
rep:				<a class="btn-general" href="https://1fichier.com/login.pl" title="Login">My Account</a>
rep:			
rep:			
rep:		</div>
rep:		<div class="spacer"></div>
rep:	</div>
rep:</div>
rep:
rep:<div class="spacer spacer-20"></div>
rep:
rep:<div class="center-container2">
rep:
rep:  
rep:    <div style="margin:auto;width:700px;text-align:center;padding:5px;padding-bottom:20px">
rep:      <div class="box_header">Premium Offer <a href="https://1fichier.com/hlp.html#pourquoipremium"><img src="https://img.1fichier.com/icons/icon_question.png" style="width:18px;vertical-align:bottom" /></a></div>
rep:	    <table class="premium" cellspacing="4" style="width:400px;margin:auto;text-align:left">
rep:   	    <tr><td class="normal"><img src="https://img.1fichier.com/icons/ok-normal.png" style="width:14px" /> You are looking for a reliable and secure hosting ?</td></tr>
rep:        <tr><td class="normal"><img src="https://img.1fichier.com/icons/ok-normal.png" style="width:14px" /> Unlimited Secure Storage</td></tr>
rep:        <tr><td class="normal"><img src="https://img.1fichier.com/icons/ok-normal.png" style="width:14px" /> No advertizing</td></tr>
rep: 	      <tr><td class="normal"><img src="https://img.1fichier.com/icons/ok-normal.png" style="width:14px" /> Unlimited speed</td></tr>
rep:   	    <tr><td class="normal orange" style="font-size:16px"><img src="https://img.1fichier.com/icons/ok-normal.png" style="width:16px" /> Go to the Premium Offer !</td></tr>
rep:      </table>
rep:      <span class="spacer spacer-10"></span>
rep: 	    
rep:        <span>After trying for free the services, choose your offer :</span>
rep: 	    
rep:      <span class="spacer spacer-10"></span>
rep:			<table class="premium" style="width:650px;margin:auto" cellspacing="4">
rep:				<tr>
rep:					<td class="orange" style="padding:5px;cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=7'"><a href="https://1fichier.com/console/abo.pl?abo=7" style="color:white;font-weight:bold;font-size:+1.5em">24 h</a></td>
rep:					<td class="orange" style="padding:5px;cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=1'"><a href="https://1fichier.com/console/abo.pl?abo=1" style="color:white;font-weight:bold;font-size:+1.5em">1 month</a></td>
rep:					<td class="orange" style="padding:5px;cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=5'"><a href="https://1fichier.com/console/abo.pl?abo=5" style="color:white;font-weight:bold;font-size:+1.5em">3 months</a></td>
rep:					<td class="orange" style="padding:5px;cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=2'"><a href="https://1fichier.com/console/abo.pl?abo=2" style="color:white;font-weight:bold;font-size:+1.5em">6 months</a></td>
rep:					<td class="orange" style="padding:5px;cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=3'"><a href="https://1fichier.com/console/abo.pl?abo=3" style="color:white;font-weight:bold;font-size:+1.5em">1 year</a></td>
rep:					<td class="orange" style="padding:5px;cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=8'"><a href="https://1fichier.com/console/abo.pl?abo=8" style="color:white;font-weight:bold;font-size:+1.5em">LifeTime</a></td>
rep:				</tr>
rep:				<tr>
rep:					<td class="normal" style="cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=7'"><a href="https://1fichier.com/console/abo.pl?abo=7" style="font-weight:bold;font-size:+1.5em">1 &euro;</a></td>
rep:					<td class="normal" style="cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=1'"><a href="https://1fichier.com/console/abo.pl?abo=1" style="font-weight:bold;font-size:+1.5em">3 &euro;</a></td>
rep:					<td class="normal" style="cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=5'"><a href="https://1fichier.com/console/abo.pl?abo=5" style="font-weight:bold;font-size:+1.5em">9 &euro;</a></td>
rep:					<td class="normal" style="cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=2'"><a href="https://1fichier.com/console/abo.pl?abo=2" style="font-weight:bold;font-size:+1.5em">15 &euro;</a></td>
rep:					<td class="normal" style="cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=3'"><a href="https://1fichier.com/console/abo.pl?abo=3" style="font-weight:bold;font-size:+1.5em">30 &euro;</a></td>
rep:					<td class="normal" style="cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=8'"><a href="https://1fichier.com/console/abo.pl?abo=8" style="font-weight:bold;font-size:+1.5em">99 &euro;</a></td>
rep:				</tr>
rep:			</table>
rep: 	    <span class="spacer spacer-10"></span>
rep:      Price from, depending on the <a style="text-decoration:underline" href="https://1fichier.com/hlp.html#modereglement" target="_blank">payment method</a>.
rep:      <br/><a style="text-decoration:underline" href="https://1fichier.com/hlp.html#politiquetarifs" target="_blank">Pricing Policy</a>
rep: 	  </div>
rep:
rep:	  
rep:      <span class="spacer spacer-10"></span>
rep:      <div style="width:750px;height:110px;margin:auto;text-align:center;vertical-align:middle;overflow:hidden;padding:2px">
rep:				
rep:<script type="text/javascript">
rep:var zone = "DZ-fYp5aMrTlK-sgoE";
rep:var data = null;
rep:var protocol = '//event.ohmyad.co/dispatch/' + zone + '?data=' + data;
rep:document.write('<scr' + 'ipt language="javascript" src="' + protocol  + '"></scr' + 'ipt>');
rep:</script>
rep:  	  </div>
rep:		
rep:
rep:  
rep:
rep:  <span class="spacer spacer-10"></span>
rep:
rep:  <form accept-charset="UTF-8" method="post" action="https://1fichier.com/?kvs8aox113" style="margin:auto">
rep:    <div style="width:900px;margin:auto;padding:10px;text-align:center;vertical-align:middle;overflow:hidden">
rep:      
rep:
rep:     
rep:    <span class="spacer spacer-5"></span>
rep:    <img style="padding:5px;vertical-align:middle;float:left" src="https://1fichier.com/qr.pl?do=0.kvs8aox113&s=1" width="148" height="148" />
rep:    <table class="premium" style="width:680px;margin:10px auto;float:right" cellspacing="4">
rep:     
rep:            <tr>
rep:              <td class="titre normal" style="width:180px">File Name :</td>
rep:              <td class="normal">Ant-Man.2015.REAL.RERIP.MULTI.1080p.BluRay.x264.AC3.DTS-ShowFr.zone-telechargement.com.mkv</td>
rep:            </tr>
rep:            <tr>
rep:              <td class="titre normal">Date :</td>
rep:              <td class="normal">19/11/2015</td>
rep:            </tr>
rep:            <tr>
rep:              <td class="titre normal">Size :</td>
rep:              <td class="normal">9.11 GB</td>
rep:            </tr>
rep:            
rep:          
rep:        </table>
rep:        <span class="spacer spacer-5"></span>
rep:    </div>
rep:
rep:    <span class="spacer spacer-10"></span>
rep:
rep:    <div style="width:500px;margin:auto;padding:10px;text-align:center;vertical-align:middle">
rep:        
rep:
rep:        
rep:        <input type="submit" value="Access to download" style="float:none;margin:auto;font-weight:bold;width:300px;height:50px;font-size:14px;border:2px solid red" class="ok btn-general btn-orange" />
rep:        <span class="spacer spacer-10"></span>
rep:        <div style="width:280px;margin:auto;text-align:left">
rep:	        <input type="checkbox" name="dl_no_ssl" />&nbsp;Download without SSL encryption <a href="https://1fichier.com/hlp.html#securitesite"><img src="https://img.1fichier.com/icons/icon_question.png" style="width:18px;vertical-align:bottom" /></a>
rep:  	      <span class="spacer spacer-10"></span>
rep:    	    <input type="checkbox" name="dlinline" />&nbsp;Inline Download <a href="https://1fichier.com/hlp.html#dispositioninline"><img src="https://img.1fichier.com/icons/icon_question.png" style="width:18px;vertical-align:bottom" /></a>
rep:	        
rep:        </div>
rep:        <span class="spacer spacer-10"></span>
rep:    </div>
rep:  </form>
rep:
rep:</div>
rep:<div id="footer">
rep:	<div class="center-container">
rep:		<a href="https://1fichier.com" title="Back to home page"><img class="gauche" src="https://img.1fichier.com/logo-footer.png" alt="1fichier.com" /></a>
rep:		<div id="link-container">
rep:			<a href="https://1fichier.com/legal.html">Legal</a>&nbsp;&nbsp;&nbsp;
rep:			<a href="https://1fichier.com/cgu.html">Terms Of Use</a>&nbsp;&nbsp;&nbsp;
rep:			<a href="https://1fichier.com/abus.html">Abuse</a>&nbsp;&nbsp;&nbsp;
rep:			<a href="https://1fichier.com/tarifs.html">Prices</a>&nbsp;&nbsp;&nbsp;
rep:			<a href="https://1fichier.com/revendeurs.html">Resellers</a>&nbsp;&nbsp;&nbsp;
rep:			<a href="https://1fichier.com/hlp.html">Help</a>&nbsp;&nbsp;&nbsp;
rep:			<a href="https://1fichier.com/network.html">Network</a>&nbsp;&nbsp;&nbsp;
rep:			<a href="https://1fichier.com/contact.html">Contact</a>
rep:      <br/>
rep:      <a target="_new" href="https://twitter.com/1fichiercom"><img src="https://img.1fichier.com/twitter.png" alt="Twitter" style="padding:0;border:0" /></a>&nbsp;&nbsp;&nbsp;
rep:      <a target="_new" href="https://facebook.com/1fichiercom"><img src="https://img.1fichier.com/facebook.png" alt="Facebook" style="padding:0;border:0" /></a>&nbsp;&nbsp;&nbsp;
rep:      <a target="_new" href="https://dstorage.fr" style="vertical-align:top">DStorage SASU © 2009-2015</a>
rep:		</div>
rep:	</div>
rep:	<span class="spacer"></span>
rep:</div>       
rep:
rep:
rep:
rep:	
rep:	  <script type="text/javascript" src="//as.ebz.io/api/choixPubJS.htm?pid=1123851&screenLayer=1&mode=NONE&home=https://1fichier.com"></script>
rep:		<script type='text/javascript' src='//pl106067.puhtml.com/95/d1/52/95d152218ed07b10b671b53f4b8d8805.js'></script>
rep:	
rep:
rep:
rep:<script type="text/javascript">
rep:  var _paq = _paq || [];
rep:  _paq.push(["setCookieDomain", "*.1fichier.com"]);
rep:  _paq.push(["setDoNotTrack", true]);
rep:  _paq.push(['trackPageView']);
rep:  _paq.push(['enableLinkTracking']);
rep:  (function() {
rep:    var u="//st-1.1fichier.com/";
rep:    _paq.push(['setTrackerUrl', u+'piwik.php']);
rep:    _paq.push(['setSiteId', 2]);
rep:    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
rep:    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
rep:  })();
rep:</script>
rep:<noscript><p><img src="//st-1.1fichier.com/piwik.php?idsite=2" style="border:0;" alt="" /></p></noscript>
rep:
rep:</body>
rep:</html>
rep: === CURL END ===
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0 --silent --include -b /tmp/plowdown.18825.1343 -b LG=en -d  --referer https://1fichier.com/?kvs8aox113 https://1fichier.com/?kvs8aox113
rep: Received 11738 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep:HTTP/1.1 200 OK
rep:Server: nginx
rep:Date: Tue, 22 Dec 2015 22:36:58 GMT
rep:Content-Type: text/html; charset=utf-8
rep:Transfer-Encoding: chunked
rep:Connection: keep-alive
rep:Vary: Accept-Encoding
rep:Cache-Control: no-cache
rep:Expires: Fri, 30 Oct 1998 14:19:41 GMT
rep:Content-Encoding: gzip
rep:
rep:<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
rep:	"http://www.w3.org/TR/html4/strict.dtd">
rep:<html lang="en">
rep:	<head>
rep:    <title>1fichier.com: Cloud Storage</title>
rep:		<meta name="robots" content="noindex" />
rep:    <meta http-equiv="content-type" content="text/html;charset=utf-8">
rep:    <link rel="shortcut icon" href="https://img.1fichier.com/favicon.ico" />
rep:    <link rel="icon" type="image/x-icon" href="https://img.1fichier.com/favicon.ico" />
rep:    <link rel="icon" type="image/png" href="https://img.1fichier.com/favicon.png" />
rep:    <link rel="apple-touch-icon" href="https://img.1fichier.com/favicon.png" />
rep:    <link rel="image_src" href="https://img.1fichier.com/favicon.png" />
rep:    <link rel="stylesheet" type="text/css" href="https://img.1fichier.com/css/style.css" />
rep:    <link rel="stylesheet" type="text/css" href="https://img.1fichier.com/css/jquery.ui.css" />
rep:    <script type="text/javascript" src="https://img.1fichier.com/js/jquery.js"></script>
rep:</head>
rep:<body>
rep:<div id="header" class="bloc">
rep:	<div class="center-container">
rep:		<a href="https://1fichier.com" title="1fichier.com"><img id="logo" src="https://img.1fichier.com/logo.png" alt="logo" width="240" height="70" style="margin-top:5px" /></a>
rep:
rep:		<div id="btn-container">
rep:			<div class="select-container ddh" style="width:150px">
rep:    		<select class="dropdown" onchange="window.location.href=this.value">
rep:		      <option value="/?kvs8aox113&amp;lg=fr" data-imagesrc="https://img.1fichier.com/flags/fr.png">Francais</option>
rep:    		  <option value="/?kvs8aox113&amp;lg=bg" data-imagesrc="https://img.1fichier.com/flags/bg.png">Български</option>
rep:		      <option value="/?kvs8aox113&amp;lg=cn" data-imagesrc="https://img.1fichier.com/flags/cn.png">中文（简体）</option>
rep:		      <option value="/?kvs8aox113&amp;lg=en" data-imagesrc="https://img.1fichier.com/flags/en.png" selected="selected">English</option>
rep:		      <option value="/?kvs8aox113&amp;lg=es" data-imagesrc="https://img.1fichier.com/flags/es.png">Español</option>
rep:		      <option value="/?kvs8aox113&amp;lg=in" data-imagesrc="https://img.1fichier.com/flags/in.png">हिंदी</option>
rep:		      <option value="/?kvs8aox113&amp;lg=pl" data-imagesrc="https://img.1fichier.com/flags/pl.png">Polski</option>
rep:					<option value="/?kvs8aox113&amp;lg=pt" data-imagesrc="https://img.1fichier.com/flags/pt.png">Português</option>
rep:		      <option value="/?kvs8aox113&amp;lg=tr" data-imagesrc="https://img.1fichier.com/flags/tr.png">Türkçe</option>
rep:					<option value="/?kvs8aox113&amp;lg=ru" data-imagesrc="https://img.1fichier.com/flags/ru.png">Русский</option>
rep:		    </select>
rep:			</div>
rep:
rep:			<a class="btn-general btn-gris-clair" href="https://1fichier.com/tarifs.html" title="Prices">Prices</a>
rep:
rep:			
rep:				<a class="btn-general btn-orange" href="https://1fichier.com/register.pl" title="Register">Register</a>
rep:				<a class="btn-general" href="https://1fichier.com/login.pl" title="Login">My Account</a>
rep:			
rep:			
rep:		</div>
rep:		<div class="spacer"></div>
rep:	</div>
rep:</div>
rep:
rep:<div class="spacer spacer-20"></div>
rep:
rep:<div class="center-container2">
rep:
rep:    <div style="margin:auto;width:700px;text-align:center;padding:5px;padding-bottom:20px">
rep:      <div class="box_header">Premium Offer <a href="https://1fichier.com/hlp.html#pourquoipremium"><img src="https://img.1fichier.com/icons/icon_question.png" style="width:18px;vertical-align:bottom" /></a></div>
rep:	    <table class="premium" cellspacing="4" style="width:400px;margin:auto;text-align:left">
rep:   	    <tr><td class="normal"><img src="https://img.1fichier.com/icons/ok-normal.png" style="width:14px" /> You are looking for a reliable and secure hosting ?</td></tr>
rep:        <tr><td class="normal"><img src="https://img.1fichier.com/icons/ok-normal.png" style="width:14px" /> Unlimited Secure Storage</td></tr>
rep:        <tr><td class="normal"><img src="https://img.1fichier.com/icons/ok-normal.png" style="width:14px" /> No advertizing</td></tr>
rep: 	      <tr><td class="normal"><img src="https://img.1fichier.com/icons/ok-normal.png" style="width:14px" /> Unlimited speed</td></tr>
rep:   	    <tr><td class="normal orange" style="font-size:16px"><img src="https://img.1fichier.com/icons/ok-normal.png" style="width:16px" /> Go to the Premium Offer !</td></tr>
rep:      </table>
rep:      <span class="spacer spacer-10"></span>
rep:        <span>After trying for free the services, choose your offer :</span>
rep:      <span class="spacer spacer-10"></span>
rep:			<table class="premium" style="width:650px;margin:auto" cellspacing="4">
rep:				<tr>
rep:					<td class="orange" style="padding:5px;cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=7'"><a href="https://1fichier.com/console/abo.pl?abo=7" style="color:white;font-weight:bold;font-size:+1.5em">24 h</a></td>
rep:					<td class="orange" style="padding:5px;cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=1'"><a href="https://1fichier.com/console/abo.pl?abo=1" style="color:white;font-weight:bold;font-size:+1.5em">1 month</a></td>
rep:					<td class="orange" style="padding:5px;cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=5'"><a href="https://1fichier.com/console/abo.pl?abo=5" style="color:white;font-weight:bold;font-size:+1.5em">3 months</a></td>
rep:					<td class="orange" style="padding:5px;cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=2'"><a href="https://1fichier.com/console/abo.pl?abo=2" style="color:white;font-weight:bold;font-size:+1.5em">6 months</a></td>
rep:					<td class="orange" style="padding:5px;cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=3'"><a href="https://1fichier.com/console/abo.pl?abo=3" style="color:white;font-weight:bold;font-size:+1.5em">1 year</a></td>
rep:					<td class="orange" style="padding:5px;cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=8'"><a href="https://1fichier.com/console/abo.pl?abo=8" style="color:white;font-weight:bold;font-size:+1.5em">LifeTime</a></td>
rep:				</tr>
rep:				<tr>
rep:					<td class="normal" style="cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=7'"><a href="https://1fichier.com/console/abo.pl?abo=7" style="font-weight:bold;font-size:+1.5em">1 &euro;</a></td>
rep:					<td class="normal" style="cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=1'"><a href="https://1fichier.com/console/abo.pl?abo=1" style="font-weight:bold;font-size:+1.5em">3 &euro;</a></td>
rep:					<td class="normal" style="cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=5'"><a href="https://1fichier.com/console/abo.pl?abo=5" style="font-weight:bold;font-size:+1.5em">9 &euro;</a></td>
rep:					<td class="normal" style="cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=2'"><a href="https://1fichier.com/console/abo.pl?abo=2" style="font-weight:bold;font-size:+1.5em">15 &euro;</a></td>
rep:					<td class="normal" style="cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=3'"><a href="https://1fichier.com/console/abo.pl?abo=3" style="font-weight:bold;font-size:+1.5em">30 &euro;</a></td>
rep:					<td class="normal" style="cursor:pointer;cursor:hand" onclick="window.location.href='https://1fichier.com/console/abo.pl?abo=8'"><a href="https://1fichier.com/console/abo.pl?abo=8" style="font-weight:bold;font-size:+1.5em">99 &euro;</a></td>
rep:				</tr>
rep:			</table>
rep: 	    <span class="spacer spacer-10"></span>
rep:      Price from, depending on the <a style="text-decoration:underline" href="https://1fichier.com/hlp.html#modereglement" target="_blank">payment method</a>.
rep:      <br/><a style="text-decoration:underline" href="https://1fichier.com/hlp.html#politiquetarifs" target="_blank">Pricing Policy</a>
rep: 	  </div>
rep:
rep:      <span class="spacer spacer-10"></span>
rep:      <div style="width:750px;height:110px;margin:auto;text-align:center;vertical-align:middle;overflow:hidden;padding:2px">
rep:        
rep:<script type="text/javascript">
rep:var zone = "DZ-fYp5aMrTlK-sgoE";
rep:var data = null;
rep:var protocol = '//event.ohmyad.co/dispatch/' + zone + '?data=' + data;
rep:document.write('<scr' + 'ipt language="javascript" src="' + protocol  + '"></scr' + 'ipt>');
rep:</script>
rep:      </div>
rep:
rep:  <span class="spacer spacer-10"></span>
rep:  <div style="margin:auto;text-align:center;font-size:16px;padding:10px;font-weight:bold;width:580px">
rep:    
rep:			To help you discover our services, we will not limit your download speed.
rep:    
rep:  </div>
rep:  <span class="spacer spacer-10"></span>
rep:  <div style="width:600px;height:300px;margin:auto;text-align:center;vertical-align:middle">
rep:      <a href="https://c-6.1fichier.com/c2051390700"  style="float:none;margin:auto;font-weight:bold;padding: 10px;margin: 10px;font-size:+1.6em;border:2px solid red" class="ok btn-general btn-orange">Click here to download the file</a>
rep:  </div>
rep:
rep:  <span class="spacer spacer-10"></span>
rep:</div>
rep:<div id="footer">
rep:	<div class="center-container">
rep:		<a href="https://1fichier.com" title="Back to home page"><img class="gauche" src="https://img.1fichier.com/logo-footer.png" alt="1fichier.com" /></a>
rep:		<div id="link-container">
rep:			<a href="https://1fichier.com/legal.html">Legal</a>&nbsp;&nbsp;&nbsp;
rep:			<a href="https://1fichier.com/cgu.html">Terms Of Use</a>&nbsp;&nbsp;&nbsp;
rep:			<a href="https://1fichier.com/abus.html">Abuse</a>&nbsp;&nbsp;&nbsp;
rep:			<a href="https://1fichier.com/tarifs.html">Prices</a>&nbsp;&nbsp;&nbsp;
rep:			<a href="https://1fichier.com/revendeurs.html">Resellers</a>&nbsp;&nbsp;&nbsp;
rep:			<a href="https://1fichier.com/hlp.html">Help</a>&nbsp;&nbsp;&nbsp;
rep:			<a href="https://1fichier.com/network.html">Network</a>&nbsp;&nbsp;&nbsp;
rep:			<a href="https://1fichier.com/contact.html">Contact</a>
rep:      <br/>
rep:      <a target="_new" href="https://twitter.com/1fichiercom"><img src="https://img.1fichier.com/twitter.png" alt="Twitter" style="padding:0;border:0" /></a>&nbsp;&nbsp;&nbsp;
rep:      <a target="_new" href="https://facebook.com/1fichiercom"><img src="https://img.1fichier.com/facebook.png" alt="Facebook" style="padding:0;border:0" /></a>&nbsp;&nbsp;&nbsp;
rep:      <a target="_new" href="https://dstorage.fr" style="vertical-align:top">DStorage SASU © 2009-2015</a>
rep:		</div>
rep:	</div>
rep:	<span class="spacer"></span>
rep:</div>       
rep:
rep:
rep:
rep:	
rep:	  <script type="text/javascript" src="//as.ebz.io/api/choixPubJS.htm?pid=1123851&screenLayer=1&mode=NONE&home=https://1fichier.com"></script>
rep:		<script type='text/javascript' src='//pl106067.puhtml.com/95/d1/52/95d152218ed07b10b671b53f4b8d8805.js'></script>
rep:	
rep:
rep:
rep:<script type="text/javascript">
rep:  var _paq = _paq || [];
rep:  _paq.push(["setCookieDomain", "*.1fichier.com"]);
rep:  _paq.push(["setDoNotTrack", true]);
rep:  _paq.push(['trackPageView']);
rep:  _paq.push(['enableLinkTracking']);
rep:  (function() {
rep:    var u="//st-1.1fichier.com/";
rep:    _paq.push(['setTrackerUrl', u+'piwik.php']);
rep:    _paq.push(['setSiteId', 2]);
rep:    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
rep:    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
rep:  })();
rep:</script>
rep:<noscript><p><img src="//st-1.1fichier.com/piwik.php?idsite=2" style="border:0;" alt="" /></p></noscript>
rep:
rep:</body>
rep:</html>
rep: === CURL END ===
dbg: arbitrary wait (from module)
Waiting 300 seconds...

**Comment by ericb48** [comment]
1fichier.com have add a new advertising page with this text "To help you discover our services, we will not limit your download speed." and we need to click on button to start download.
I thing that this page don't be here for a long time

**Comment by f0c4l** [comment]
Thank you ! 
I confirm it works for me.
Happy New Year !
