### ISSUE TITLE
Select directory for upload with 1fichier

### ISSUE THREAD

**Issue by kidburglar** [mcrapet/plowshare-modules-legacy#57]
Hello, I saw the note in 1fichier.sh that you will see it later.
I can maybe help but before I will ask how you saw this option ?

So it keep the same code idea.

Cheers

**Comment by Raziel-23** [comment]
There are already modules with --folder option, you can check which support it:
``` plowup -H | less -p '--folder' ```
If you will be able to implement it feel free to do it. I'm not familiar with uploading yet, so I will not be able to help you.

**Comment by kidburglar** [comment]
Thanks, I forgot that some modules support it.
I will look and try to implement it for 1fichier.

Cheers
