### ISSUE TITLE
keep2share has changed

### ISSUE THREAD

**Issue by idleloop-github** [mcrapet/plowshare-modules-legacy#58]
keep2share seems to have changed, and now detects plowshare as a bot.

**Comment by Raziel-23** [comment]
You have to be more specific. I presume that it concerns downloading. For me it works with this test file:

``` http://k2s.cc/file/445d948518bd1/Test_file_50MB.zip ```

A month ago [here](https://github.com/mcrapet/plowshare/issues/35) someone else also report an issue with keep2share. Maybe this is a geographical restriction. Please post somewhere your log (like pastebin) with this options:

``` plowdown -v4 -r0 --no-plowsharerc --no-color <url> &>log.txt ```

Remember that logs can contain your credentials. Be sure to remove them before posting.

**Comment by idleloop-github** [comment]
$ plowdown -v4 -r0 --no-plowsharerc --no-color 'http://keep2share.cc/file/445d948518bd1/Test_file_50MB.zip' &>log.txt

https://paste.ee/p/kX5bP

This page doesn't appear using a web browser.

**Comment by Raziel-23** [comment]
Very useful log. Here how the page looks like from your log:

https://imgur.com/GoPLWWi

I prepare a patch for this verification from your log, but you have to test it before I will push it to master. It was a half blindly coding because I cannot trigger this verification page. I don't know how the next page looks if we successfully resolved recaptcha. I suspect that 'Location' is set in a header, but maybe I'm wrong.

**Comment by Raziel-23** [comment]
One more version. I change recaptcha PUBKEY because apparently it is different then below in the code.

**Comment by Raziel-23** [comment]
One more version. I forgot to load a page after successfully resolving recaptcha. I will probably modify this patch, because I suspect that it will not work after first try. Nevertheless we are closer to resolve this issue.

**Comment by idleloop-github** [comment]
Hi Raziel-23,
I'm **deeply** sorry to recognize :-( that it's been my fault: I was using a testing platform and it was inadvertently going out throu a 3rd party proxy, so k2s server is probably right on trying to check that I was a human... through a normal internet connection everything is ok. Nonetheless, I tested the patch: it didn't work but because I had no answer from the server after sending a correct captcha value... again it's probably due to the specifics of a collapsed proxy - I couldn't find another reason. Hope the code u developed can be more usefully used in the future :-(

**Comment by Raziel-23** [comment]
No problem, I will close this issue. Good to know what was a cause.
