### ISSUE TITLE
zippyshare download error

### ISSUE THREAD

**Issue by crazycatdevs** [mcrapet/plowshare-modules-legacy#6]
zippyshare seems to have changed its system:

> plowdown -v4 http://www41.zippyshare.com/v/uZjTVyA6/file.html
> rep: === SYSTEM INFO BEGIN ===
> rep: [mach] debian x86_64 linux-gnu x86_64-pc-linux-gnu
> rep: [bash] 4.2.37(1)-release
> rep: [curl] curl 7.26.0 (x86_64-pc-linux-gnu) libcurl/7.26.0 OpenSSL/1.0.1e zlib/1.2.7 libidn/1.25 libssh2/1.4.2 librtmp/2.3
> rep: [sed ] GNU sed version 4.2.1
> rep: [lib ] '/usr/local/share/plowshare4'
> rep: === SYSTEM INFO END ===
> rep: plowdown version v1.1.0-29-g0df22d0 (2015-01-06)
> rep: use /etc/plowshare.conf
> Starting download (zippyshare): http://www41.zippyshare.com/v/uZjTVyA6/file.html
> rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0 --max-redirs 5 --silent -L -c /tmp/plowdown.29575.7219 -b ziplocale=en http://www41.zippyshare.com/v/uZjTVyA6/file.html
> rep: Received 28333 bytes. DRETVAL=0
> rep: === CURL BEGIN ===
> rep:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
> rep:    <html xmlns:fb="http://ogp.me/ns/fb#">
> rep:        <head>
> rep:            <title>Zippyshare.com - testpic.jpg</title>
> rep:                <meta http-equiv="content-type" content="text/html; charset=utf-8">
> rep:                <meta name="robots" content="index, follow, noarchive, all">
> rep:                <meta name="keywords" content="">
> rep:                <meta name="description" content="">
> rep:            <meta property="og:type" content="image" />
> rep:                <meta property="og:description" content="Zippyshare.com - Free File Hosting" />
> rep:                <meta property="og:image" content="http://www41.zippyshare.com/scaled/uZjTVyA6/file.html" />
(...)
> rep: === CURL END ===
> dbg: Content Type: 'image'
> rep: interpreter: /usr/bin/js
> rep: === JAVASCRIPT BEGIN ===
> rep:var elts = new Array();
> rep:        var document = {
> rep:          getElementById: function(id) {
> rep:            if (! elts[id]) { elts[id] = {}; }
> rep:            return elts[id];
> rep:          }
> rep:        };
> rep:
> rep:        var curobj;
> rep:        evt = {
> rep:          originalEvent: 1
> rep:        }
> rep:
> rep:        mouseevent = function(fnt) {
> rep:          fnt.apply(this,[evt]);
> rep:        }
> rep:        attr = function(attributeName, value) {
> rep:          if (attributeName === 'href') {
> rep:            document.getElementById(curobj.substr(1)).href = value;
> rep:          }
> rep:        }
> rep:        $ = function(obj) {
> rep:          curobj=obj;
> rep:          return {
> rep:            ready: mouseevent,
> rep:            mouseenter: mouseevent,
> rep:            mouseover: mouseevent,
> rep:            attr: attr
> rep:          };
> rep:        }
> rep:
> rep:        delete(java);
> rep:        var EnvJs = true;
> rep:
> rep:            var a = function() {return 1};
> rep:    var b = function() {return a() + 1};
> rep:    var c = function() {return b() + 1};
> rep:    var d = document.getElementById('omg').getAttribute('class');
> rep:    if (true) { d = d*2;}
> rep:    document.getElementById('dlbutton').href = "/d/uZjTVyA6/"+(901565%1000 + a() + b() + c() + d + 5/5)+"/testpic.jpg";
> rep:    if (document.getElementById('fimage')) {
> rep:        document.getElementById('fimage').href = "/i/uZjTVyA6/"+(901565%1000 + a() + b() + c() + d + 5/5)+"/testpic.jpg";
> rep:    }
> rep:        print(elts['fimage'].href);
> rep: === JAVASCRIPT END ===
> js: uncaught JavaScript runtime exception: TypeError: Cannot find function getAttribute in object [object Object].
> 
> Output URL is not valid: http://www41.zippyshare.com

**Comment by crazycatdevs** [comment]
@mcrapet : I did tries, but I can't understand how to add the `getAttribute` method to the document.getElementById in this module...
Any idea ?

**Comment by mcrapet** [comment]
Could you test using:
4992db364e76199ed21e7ccc7a183d3810d74dcc

**Comment by crazycatdevs** [comment]
Works ! Thanks a lot @mcrapet , good job !
