### ISSUE TITLE
1fichier (upload) we cannot create a folder with a '+'

### ISSUE THREAD

**Issue by kidburglar** [mcrapet/plowshare-modules-legacy#68]
Hello again,

A friend found another problem with 1fichier upload.
If we use a '+' we have a match, parse problem but we can deal with it if we replace '+' with '\+'.

The second problem is that 1fichier use the hex representation to create the directory exemple '+' is '%2B'. We can well replace each symbol manually but I don't know if there is a better approach.

Cheers.

**Comment by Raziel-23** [comment]
`DIR=$(uri_encode_strict <<< "$DIR")`
[API list](https://github.com/mcrapet/plowshare/wiki/API), I don't know if there are all listed function, but probably most of them.

**Comment by kidburglar** [comment]
Thanks I not saw it. The PR is #69
