### ISSUE TITLE
Zippyshare Syntax Error Again

### ISSUE THREAD

**Issue by amintalkin** [mcrapet/plowshare-modules-legacy#77]
Again Zippyshare may have changed its code.
```
root@host [~]# plowdown http://www65.zippyshare.com/v/45917134/file.html
Starting download (zippyshare): http://www65.zippyshare.com/v/45917134/file.html
/tmp/plowdown.30462.6337.js:17: SyntaxError: syntax error:
/tmp/plowdown.30462.6337.js:17:             </div>
/tmp/plowdown.30462.6337.js:17: ............^
Output URL is not valid: http://www65.zippyshare.com
root@host [~]#
```

**Comment by Raziel-23** [comment]
This is the same error as you described here #76. For me it downloads properly. You simply didn't update your modules. Please update your modules with command: `plowmod -u`

**Comment by amintalkin** [comment]
You are correct. I Updated the module for global users but forgot to update for specific root user.

I have created download module for userscloud and filescdn. They may be buggy but works for me. Shall I share it? Actually its similar to lunatic files.

**Comment by Raziel-23** [comment]
Please create a pull requests for each module. They will be reviewed and improved if it's necessary.
