### ISSUE TITLE
FileJoker Premium download not working

### ISSUE THREAD

**Issue by lddd** [mcrapet/plowshare-modules-legacy#78]
Hi there,

testing to get some files with plowdown on FileJoker.net. I have premium account there and using command as following

plowdown -a 'my@mail.com:password' https://filejoker.net/29ir... 

The result is it tries to download it as free user

`filejoker: unused command line switches: -a my@mail.com:password
Starting download (filejoker): https://filejoker.net/29irc...
Waiting 121 seconds... 1m57s left^C
`
Any ideas whats wrong here?

**Comment by mcrapet** [comment]
Hi,

Have in README.md module matrix:
https://github.com/mcrapet/plowshare-modules-legacy

You'll see that only anonymous download is supported.

**Comment by Raziel-23** [comment]
@lddd If you have a premium account then I can add support for it. I will only need access to it or collaboration from your side.

**Comment by lddd** [comment]
Can do this my self. Just wanted to know why its not supporting premium accounts as on all other hosts. I think without it its pretty much useless. but thanks anyways.

**Comment by Raziel-23** [comment]
I don't spend my money for a premium account only to implement support for it. I only add support for it if someone wants it. Furthermore I'm not an author of this module.

I can help you. I can prepare a login function. You will just test it for a premium account and implement premium download.

**Comment by Raziel-23** [comment]
@lddd I implemented a login function for free and premium accounts. It should work for premium accounts, but you have to test it. I prepared a preliminary code for premium accounts. Here you should implement support for premium accounts:
https://github.com/mcrapet/plowshare-modules-legacy/blob/35a460e790438412826d7e6119ff0778130410f2/filejoker.sh#L165
You just have to find a final download link ("$FILE_URL") on a page. For premium accounts it should not be hard. Don't hesitate if you have questions how to implement it. Make a pull request when you will be ready.

**Comment by Raziel-23** [comment]
It seems that the OP is not interested in resolving this issue. Without access to a premium account I can't help, so I'm closing this issue.

**Comment by masneg** [comment]
Hi Raziel. I can give you my premium account to test it.
Is it possible for you to fix the filejoker plugin?
How can i send you the details of my account?
thanks in advance.
