### ISSUE TITLE
mediafire has just changed their captchas ?

### ISSUE THREAD

**Issue by pyed** [mcrapet/plowshare-modules-legacy#80]
mediafire was working for me just fine today, I was entering captchas when I'm prompted for one and I keep going, until something happened that would give me `Unexpected content/captcha type. Site updated?`

I opened the url in my browser to see the captcha and I noticed that it was different than the ones I was getting, could be the reason ?

here's an `-v4` run: http://sprunge.us/SfRR

I tried dozens of mediafire urls and they gave me the same results, when I try with a different computer/IP it will download until I hit the captchas again

**Comment by Raziel-23** [comment]
Please test it. Mediafire has recaptcha and solvemedia verification mechanism. I can only trigger solvemedia, so you have to test recaptcha. I based on your log to implement recaptcha correctly, but you have to test it.

**Comment by pyed** [comment]
works again, thank you @Raziel-23

**Comment by pyed** [comment]
as soon as mediafire changed to `recaptcha` which looks like [this](http://i.imgur.com/vP5vDud.jpg) it stopped working with a different error:
```bash
parse failed (sed): "/function[[:space:]]*_/ s/^.*"\([^"]\+\)";.*$/\1/p" (skip 1)
Failed inside mediafire_download(), line 322, mediafire.sh
Failed inside mediafire_download() [1]
```

here's a lengthy `-v4` run: `http://sprunge.us/fKFU`

**Comment by Raziel-23** [comment]
Your image with recaptcha was removed from imgur. Most probably you enter wrong recaptcha. Nevertheless I improved checking if recaptcha was typed correctly. Please test it now.

**Comment by pyed** [comment]
yes they delete them after a little while, there's noway that it is that I'm entering them wrong, as I entered them like 20 times, I used imgur as a demo, I'm using iTerm2 for OS X and I edited `core.sh` so it uses [imgcat](https://www.iterm2.com/images.html), I'm not sure if that's something I should make PR for as the use case for it is pretty specific I guess.

I pulled the changes and now mediafire switched me back to solve media, thank you.

**Comment by pyed** [comment]
after your latest changes, now solve media is telling me that I entered the captcha wrong, which I'm sure I did not as i repeated that multiple times, reverting back to eb033ee fixed it.

**Comment by Raziel-23** [comment]
Solvemedia image looks like this:
![plowdown 20048 7831 solvemedia](https://cloud.githubusercontent.com/assets/8607499/15359346/2684d1f2-1d09-11e6-845f-1be01ff30edb.jpg)

Recaptcha image looks like this:
![plowdown 21956 22555 recaptcha](https://cloud.githubusercontent.com/assets/8607499/15359353/2f6bea30-1d09-11e6-9204-5b0e6eb3c637.jpg)

This checking for wrong captcha in mediafire module only apply for recaptcha, because solvemedia already has its own checking already in the core [here](https://github.com/mcrapet/plowshare/blob/master/src/core.sh#L1961). For me solvemedia works. I cannot trigger recaptcha and in this way I don't know exactly what browser send to the server and what we get from it as a response. For me it's like blind coding.

**Comment by pyed** [comment]
That's right, I encountered recaptcha yesterday and the day before after
downloading like 50 links with solvemedia, and when you hit recaptcha
you'll keep getting them for the rest of the day.

**Comment by Raziel-23** [comment]
Ok, I will be trying hit recaptcha :)

**Comment by pyed** [comment]
Hahaha, you're keen on solving this, i had like 200 files in mediafire and
now I'm done downloading them thanks to you and @mcrapet

**Comment by Raziel-23** [comment]
@pyed I just want let you know that I don't forget about this issue. For me it wasn't simply to trigger this recaptcha. It is geographic restricted, so I had to use VPN. Nevertheless I finally fixed this, see a commit message [here](https://github.com/mcrapet/plowshare-modules-legacy/commit/9c0a498e7833c6bfc6ca734bb5dcf8eddf39b607).

**Comment by pyed** [comment]
That's impressive !!!

Thank you for being awesome 👍
