### ISSUE TITLE
rapidu.net

### ISSUE THREAD

**Issue by akxx87** [mcrapet/plowshare-modules-legacy#88]
Hello
rapidu.net not working I have a premium account
and download as free user
I can give premium account test

**Comment by Raziel-23** [comment]
I didn't implement support for premium accounts, because I didn't have access to them. I will implement support for them. Please send me your premium account to my email.

**Comment by akxx87** [comment]
Hello

Rapidu.net

L: 30szybki803    Pass:  nafy7aqt


Fileshark.pl

login: SHARKY362
Password: 859cgw2h

Regards


W dniu 30.05.2016 o 20:18, Raziel-23 pisze:

**Comment by Raziel-23** [comment]
Please change your passwords now.
