### ISSUE TITLE
fileshark.pl

### ISSUE THREAD

**Issue by akxx87** [mcrapet/plowshare-modules-legacy#89]
Hello
fileshark.pl not working I have a premium account

fileshark: unused command line switches: -a SHARKY408:fnp6wfrw
Starting download (fileshark): http://fileshark.pl/pobierz/12944028/hgrme/echo-effect-2015-pl-bdrip-xvid-kit-avi
parse failed (sed): "/btn-upload-free/ s/^.*normal/\([[:digit:]]\+/[[:alnum:]]\+\).*$/\1/p" (skip 0)
Failed inside fileshark_download(), line 64, fileshark.sh
Failed inside fileshark_download() [1]

I can give premium account test

**Comment by Raziel-23** [comment]
Same reason as in your previous issue. Please send me your premium account to my email.
