### ISSUE TITLE
uptobox

### ISSUE THREAD

**Issue by shins5kai** [mcrapet/plowshare-modules-legacy#90]
I have a problemen with uptobox on two vm with two ip :

http://0bin.net/paste/T6UYvXDRbdA6IDLR#hOZnGfh6PmeyqfWnEZ31suNmu8OSqJWIVd2SSX+nGHH

Perhaps the ddos proctection of clouflare

**Comment by Raziel-23** [comment]
You are right. It is DDoS protection by CloudFlare. However it is not obvious to fix, because one parameter `jschl_answer` is generated by javascript.

**Comment by shins5kai** [comment]
No one fix that on other hoster ? ^^

**Comment by Raziel-23** [comment]
So far issues with CloudFlare only shows up on uptobox. There is implemented CloudFlare recaptcha mechanism, but not DDoS. I'm sure that is can be fixed somehow, but I'm not javascript expert.

**Comment by Raziel-23** [comment]
@shins5kai Now this protection is gone. This DDoS protection was only temporally. Please confirm. Nevertheless I have cooked some solution for this javascript, but now I don't have opportunity to test it.

**Comment by shins5kai** [comment]
Yes it work I close this issue :)
