### ISSUE TITLE
dl.free.fr

### ISSUE THREAD

**Issue by Darkitty** [mcrapet/plowshare-modules-legacy#91]
Hi,

I love so much your script. But, with dl.free.fr I have this error message:
```
parse failed (sed): "/Fichier:/ s/^.*">\([^<]*\).*$/\1/p" (skip 1)
Failed inside dl_free_fr_download(), line 171, dl_free_fr.sh
Failed inside dl_free_fr_download() [1]
```

Have you an idea for a fix ?

**Comment by Raziel-23** [comment]
The module is old and needs to be refactored. Here https://github.com/Raziel-23/plowshare-modules-legacy/commit/7d7628c567b6dd7418bd2b4ab78f60b604f5e30a is quick dirty fix for download. I don't know well this module. I removed a lot of code, maybe useful code. Therefore this commit don't deserve to be in the master branch. Feel free to use it now. When I will have more time then I will work more on this, or maybe someone else will prepare a proper fix.

**Comment by Darkitty** [comment]
Ok. Thanks a lot <3
