### ISSUE TITLE
Openload.co download problem

### ISSUE THREAD

**Issue by atrinio** [mcrapet/plowshare-modules-legacy#92]
Hello,
I have problem with dowload from openload.co, I try different file. 
jDownloader works fine for openload.

```
plowdown https://openload.co/f/...
Starting download (openload): https://openload.co/f/...
Waiting 5 seconds... done
/tmp/plowdown.532.11645.js:15:0 SyntaxError: syntax error:
/tmp/plowdown.532.11645.js:15:0 var _0x3a92=["\xC9\x28\xA1\x28\x70\x2C\x61\x2C\x63\x2C\x6B\x
/tmp/plowdown.532.11645.js:15:0 ^
Output URL expected
```

```
plowdown --version
v2.1.4-2-g0290dc1 (2016-05-15)
```
Thanks for any advice.

**Comment by Raziel-23** [comment]
Works for me. Tested with SpiderMonkey 17. What javascript interpreter you use? For sure SipderMonkey 1.8.5 won't work.

**Comment by atrinio** [comment]
I have this

```
js --help
Usage: js [options] [[script] scriptArgs*]

  The SpiderMonkey shell provides a command line interface to the
  JavaScript engine. Code and file options provided via the command
  line are run left to right. If provided, the optional script argument
  is run after all options have been processed. Just-In-Time
  compilation modes may be enabled via command line options.

Version: JavaScript-C24.8.1
```

**Comment by Raziel-23** [comment]
I tested also with SpiderMonkey 24 the following test file:
```
https://openload.co/f/u1I7LwGAplI/Test_file_5MiB.zip
```

More precisely version 24.2.0 which is a bit older then yours:
```
Usage: js [options] [[script] scriptArgs*]

  The SpiderMonkey shell provides a command line interface to the 
  JavaScript engine. Code and file options provided via the command 
  line are run left to right. If provided, the optional script argument 
  is run after all options have been processed. Just-In-Time 
  compilation modes may be enabled via command line options.

Version: JavaScript-C24.2.0
```

For sure your javascript interpret doesn't work properly. It can't deal with with obfuscated javascript code on openload like [here](https://github.com/mcrapet/plowshare-modules-legacy/issues/83#issuecomment-220240687). I can't do anything about this. You have to change javascript interpreter and check if it works.

**Comment by Raziel-23** [comment]
@atrinio Please test the above link. Also please send me to my email a link that you have a trouble, because now I have more suspicious that it is something wrong with your link.

**Comment by atrinio** [comment]
Yes, your test file works fine, but i test the other one and for some works and others no, this is strange.

**Comment by atrinio** [comment]
I probably know where is the problem, when I try download zip or rar file it work, but problem is with files like .mkv .avi. You can find sample file in google for test.

**Comment by Raziel-23** [comment]
Ok I have such link. For such links this javascript code is located somewhere else on a page then for zip/rar files. I will have to think what is the best way to solve this.

**Comment by Raziel-23** [comment]
Now it should works. Thanks for spotting this.

**Comment by atrinio** [comment]
Yes its works, thank you very much :) :+1:
