### ISSUE TITLE
Checking DepositFiles.com / DFiles.eu links with plowprobe sometimes gives false positive result 

### ISSUE THREAD

**Issue by Konstantinusz** [mcrapet/plowshare-modules-legacy#93]
Bogus links are also marked as live when I open the link in browser, but after I click on "regular download" I get the usual 30 sec counter with gray background of deleted links.

When I attach "?redirect" to the end of the links, then plowprobe gives always the proper results.

**Comment by Raziel-23** [comment]
Please give an example of such links. If you prefer you can send an email.

**Comment by Raziel-23** [comment]
Ok I have created such link. This link is detected as a normal link (at the first glance):
```
http://dfiles.eu/files/pmsw7blf9
```
But it should be detected as a dead link, and as you described when we add `?redirect` at the end of this link it is detected as a dead link.

**Comment by mcrapet** [comment]
Thanks!
